export default {
	tabbar: {
		home: 'home',
		project: 'project',
		chat: 'chat',
		me: 'me'
	},
	message: {
		myOrder: "My Order",
		agentCenter: "Agent Center",
		projectList: "Project List",
		projectTj: "Project Recommendation",
		more: "More",
		appointment: "appointment",
		releaseDate: "Release Date",
		money: "money",
		percentage: "percentage",
		pName: 'Project name',
		search: "Find Items",
		all: "all",
		commission: "Total Commission Amount",
		agentProgect: "Items Under Agency",
		comRecord: "Commission Record",
		setCommission: "Settlement Commission",
		settlementDate: "Settlement Date",
		order: "My Order",
		approved: "Approved",
		notApproved: "Not Approved",
		failed: "Failed",
		loadmoreText: "Load More",
		loadingText: "Loading",
		nomoreText: "No More",
		login: "Login",
		appName: "Hong Kong Yatai",
		mechanism: "Medical Beauty Hospital",
		aim: "Professional scientific Internet platform",
		loginText: "User Login",
		account: "Please enter your email account",
		email: "Incorrect mailbox format",
		emailText: "email account",
		code: "Enter verification code",
		pwd: "Please input a password",
		password: "Confirm password",
		register:"Registered account",
		forgot: "Forgot password",
		registerText: "register",
		confirmBtn: "confirm",
		inviter: "Inviter Email (optional)",
		wallet: "My Wallet",
		set: "Setting",
		logOut: "Log out",
		balance: "My balance",
		freeze: "Freeze balance",
		cash: "Cash withdrawal",
		cashRecord: "Cash withdrawal record",
		bank:"Bank card",
		transfer: "Transfer to",
		balanceText: "balance",
		avatar: "avatar",
		nickname: "nickname",
		mobile: "mobile",
		editPwd: "login password",
		edit: "edit",
		detail: "Project Details",
		docIntro: "Project doctor introduction",
		position: "position",
		offices: "offices",
		good: "good",
		detailIntro: "Detailed introduction",
		projectDetail: "Project Details",
		language: "language",
		english: "English",
		chinese: "Simplified Chinese",
		langSet: "Language settings",
		loading: "Loading...",
		loginPrompt: "Login prompt",
		prompt: "You have not logged in or your login has expired. Please log in again.",
		goLogin: "login",
		mobileIncorrect: "The mobile number is incorrect",
		twoPwd: "The two inputs are inconsistent",
		registSuccess: "success",
		loginSuccess: "success",
		appointmentSuccess: "Appointment succeeded",
		settled: "Settled",
		contact: "Please contact customer service for handling",
		successText: "success",
		toLogin: "You are not logged in yet, go log in.",
		withCount: "bank card",
		bankCount: "Confirm bank card number",
		withName: "bank name",
		withPwd: "withdrawal password",
		tips1: "You have not set a withdrawal password yet. please set.",
		tips2: "You have not bound a bank card number yet. please set.",
		tips3: "You have not bound a bank name yet. please set.",
		tips4: "You have not bound a bank card yet. please set.",
		goSet: "setting",
		cancel: "cancel",
		promptText: "prompt",
		withMoney: "withdrawal amount",
		withText: "withdrawable amount",
		maxWith: "maximum withdrawable cash",
		zhHant: "Traditional Chinese",
		startText: "obtain verification code",
		changeText: "X second reacquisition",
		endText: "reacquire",
		codeTipsText: "Send after the countdown ends",
		meiQia: "Meicha customer service account",
		copy: "copy",
		whatsApp: "WhatsApp customer service account",
		kefu: "customer service account",
		emptyText: "No data available",
		version: "Version",
		companyIntro: "Company Profile",
		koText: "Korean",
		attachment: "Attachment Download",
		notice: "notice",
		noticeList: "Announcement List",
		noticeDetail: "Announcement Details",
		goTo: "contact customer service",
		levelText: "agent level",
		openBank: "Bank Address",
		rebind: "rebind bank card",
		cashText: "received bank card",
		withMan: "name",
		attestation: "real name authentication",
		documentType: "document type",
		documentNum: "certificate No",
		attestationTips: "You have been authenticated by your real name, please contact customer service if you need to make changes.",
		attestationTips1: "You haven't verified your real name yet. Go to Settings.",
		attestationText: "Name bound by real-name authentication and name bound by bank card.",
		welcomeToLogin:"welcome to login",
		registerName: 'register',
		productRecDoctor: '项目推医生介绍',
		myPageAgent: 'Member',
		myPageWallet: 'Wallet',
		myPageRecharge: 'Recharge',
		myPageWithdrawal: 'Withdraw',
		blank: 'Add bank card',
		withdrawalPassword: 'Set withdrawal password',
		verificationCode: "Verification code for Email",
		transactionPasswordCodeSend : "Sending e-mail"
	}
}
