export default {
	tabbar: {
		home: '첫 페이지',
		project: '프로젝트',
		chat: '고객 서비스',
		me: '나의'
	},
	message: {
		myOrder: "개인 주문",
		agentCenter: "에이전트 센터",
		projectList: "항목 목록",
		projectTj: "프로젝트 추천",
		more: "추가",
		appointment: "예약",
		releaseDate: "게시 날짜",
		money: "프로젝트 금액",
		percentage: "프로젝트 수수료",
		search: "항목 찾기",
		all: "모두",
		commission: "커미션 총액",
		agentProgect: "프록시 항목",
		comRecord: "커미션 기록",
		setCommission: "커미션을 결산하다",
		settlementDate: "결제 날짜",
		order: "내 주문",
		approved: "감사 완료",
		notApproved: "감사 안 함",
		failed: "통과 안 함",
		loadmoreText: "추가 로드",
		loadingText: "로드 중...",
		nomoreText: "더 이상 없어요",
		login: "로그인",
		appName: "홍콩 아태",
		mechanism: "의료 미용 병원",
		aim: "전문 과학 인터넷 플랫폼",
		loginText: "사용자 로그인",
		account: "이메일 계정을 입력하세요",
		email: "메일박스 형식이 잘못되었습니다",
		emailText: "메일박스",
		code: "인증 코드를 입력하십시오",
		pwd: "암호를 입력하십시오",
		password: "암호 확인",
		register:"계정 등록",
		forgot: "암호를 잊었습니다",
		registerText: "등록",
		confirmBtn: "확인",
		inviter: "초대장 사서함 (기입 안 함)",
		wallet: "내 지갑",
		set: "설치",
		logOut: "로그인 종료",
		balance: "내 잔액",
		freeze: "잔액 동결",
		cash: "현금 인출",
		cashRecord: "현금 인출 기록",
		bank: "은행카드",
		transfer: "전입",
		balanceText: "잔액",
		avatar: "프로필 사진",
		nickname: "닉네임",
		mobile: "핸드폰 번호",
		editPwd: "로그인 암호",
		edit: "수정",
		detail: "프로젝트 상세 정보",
		docIntro: "프로젝트 의사 소개",
		position: "직위",
		offices: "과실",
		good: "잘하다",
		detailIntro: "자세히 소개",
		projectDetail: "프로젝트 상세 정보",
		language: "언어",
		english: "영어",
		chinese: "중국어 간체",
		langSet: "언어 설정",
		loading: "요청 중...",
		loginPrompt: "로그인 프롬프트",
		prompt: "로그인하지 않았거나 로그인이 만료되었습니다. 다시 로그인하십시오.",
		goLogin: "로그인",
		mobileIncorrect: "핸드폰 번호가 잘못됐어요",
		twoPwd: "두 번 입력 불일치",
		registSuccess: "등록 성공",
		loginSuccess: "로그인 성공",
		appointmentSuccess: "예약 성공",
		settled: "결제 완료",
		contact: "고객센터에 연락하여 처리하십시오",
		successText: "성공",
		toLogin: "로그인하지 않았습니다. 로그인하십시오",
		withCount: "은행카드 번호",
		bankCount: "은행카드 번호 확인",
		withName: "은행명",
		withPwd: "비밀번호 인출",
		tips1: "현금인출 비밀번호를 설정하지 않았습니다. 설정하십시오.",
		tips2: "당신은 아직 은행카드 번호를 바인딩하지 않았습니다. 설정하십시오.",
		tips3: "은행을 바인딩하지 않았습니다. 설정하십시오.",
		tips4: "아직 은행카드를 바인딩하지 않았습니다. 설정하십시오.",
		goSet: "설정",
		cancel: "취소",
		promptText: "힌트",
		withMoney: "현금 인출 금액",
		withText: "현금 인출 가능 금액",
		maxWith: "최대 현금 인출 가능",
		zhHant: "중국어 번체",
		startText: "인증 코드 가져오기",
		changeText: "X초 다시 가져오기",
		endText: "다시 가져오기",
		codeTipsText: "카운트다운 끝나고 보내드릴게요.",
		meiQia: "미국 상담 고객센터 계정",
		copy: "복제",
		whatsApp: "WhatsApp 고객 계정",
		kefu: "고객 서비스 계정",
		emptyText: "데이터 없음",
		version: "버전 번호",
		companyIntro: "회사 소개",
		koText: "한국어",
		attachment: "첨부 파일 다운로드",
		notice: "공지",
		noticeList: "공지 상세 정보",
		noticeDetail: "공지 상세 정보",
		goTo: "고객 서비스에 문의",
		levelText: "에이전트 수준",
		openBank: "계좌 개설 은행 주소",
		rebind: "카드 다시 바인딩",
		cashText: "입금 카드",
		withMan: "이름",
		attestation: "실명인증",
		documentType: "증명서 유형",
		documentNum: "증명서 번호",
		attestationTips: "당신은 이미 실명 인증을 하였으니, 변경하려면 고객센터에 연락하십시오.",
		attestationTips1: "당신은 아직 실명 검증을 하지 않았습니다, 설정으로 이동.",
		attestationText: "실명인증 바인딩의 이름과 은행카드 바인딩의 이름이 일치하지 않습니다."
	}
}
